### ISSUE TITLE
Crashes Mail

### ISSUE THREAD

**Issue by MarkSealey** [apparition47/MailTrackerBlocker#61] opened 2021-03-05 00:01 UTC
Thanks for _MailTrackerBlocker_!

Unfortunately with the Bundle enabled _Mail_ (14.0 (3654.60.0.2.21) on 11.2.2) **crashes** (usually) when moving a message and/or Deleting.

Log attached.

[Mail crash log.pdf](https://github.com/apparition47/MailTrackerBlocker/files/6087273/Mail.crash.log.pdf)

**Comment by apparition47** [comment] 2021-03-05 00:35
Duplicate of #49 #56 #59. Please try the latest 0.3.16. Already fixed there. Please reopen if you have an issue. Thanks!

**Closed** 2021-03-05 00:35 UTC
